name: Ubuntu-Testing

on:
  pull_request:
    paths:
     # - '**.jpg'
      #- '**.jpeg'
      #- '**.png'
      - '**.bat'
  push:
    branches:
      - main
    paths:
      #- '**.jpg'
      #- '**.jpeg'
      #- '**.png'
      - '**.bat'
  workflow_dispatch:
  schedule:
  - cron: "0 */24 * * *"
jobs:
   build:
    name: Machine running...
    runs-on: ubuntu-latest
    timeout-minutes: 10080
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          curl -sL https://raw.githubusercontent.com/VexterLabs/Vps/refs/heads/main/.github/workflows/Downloads.bat -o Downloads.bat
          cmd /c Downloads.bat
          
      - name: Time Counter
        run: cmd /c loop.bat
      - name: Sleep
        shell: bash
        run: sleep 15s
