name: Windows - RustDesk + Anydesk

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */24 * * *"
jobs:
   build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 10080
    
    steps:
    
      - name: Downloading & Installing Essentials
        shell: bash
        run: sleep 5s
