name: Ubuntu-Testing

on:
paths:
- '**.bat'
  workflow_dispatch:
  schedule:
  - cron: "0 */24 * * *"
jobs:
   build:
    name: Machine running...
    runs-on: ubuntu-latest
    timeout-minutes: 10080
    
    steps:
      - name: Sleeping...
        shell: bash
        run: cmd /c loop.bat
