name: Ubuntu-Testing

on:
  workflow_dispatch:
  schedule:
  - cron: "0 */24 * * *"
  jobs:
   build:
    name: Machine running...
    runs-on: ubuntu-latest
    timeout-minutes: 10080
    
    steps:
      - name: Sleeping...
        run: sleep 5s
