name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 10080
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://raw.githubusercontent.com/VexterLabs/Vps/refs/heads/main/.github/workflows/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Download and Install AnyDesk
        run: |
          Start-Process "C:\Users\Public\Desktop\AnyDesk.exe" -ArgumentList "/install", "/quiet" -Wait
          
      - name: Log In To AnyDesk
        run: cmd /c show.bat

      - name: Time Counter
        run: python time.py
